import{expect,test}from'@playwright/test'

const workspace={schema:'gasnettrace.workspace.v2',captureId:'capture-e2e',endpoints:[{id:'Server',role:'DedicatedServer',tracePath:'server.utrace',schemaVersion:2,clockSynchronized:true,clockOffsetSeconds:0,clockUncertaintySeconds:.001,netProfilerAvailable:true,eventCount:2}],coverage:[{endpoint:'Server',ascId:'18446744073709551615',mask:65535}],analysisWarnings:[],thresholds:{}}
const events=[{id:'Server:9007199254740993',endpoint:'Server',role:'DedicatedServer',type:'AbilityActivated',typeId:1,lane:3,time:1,localTime:1,asc:'/Game/PS.ASC',subject:'/Game/GA_Fire.GA_Fire_C',detail:'Accepted',spec:17,predictionCurrent:84,predictionBase:81,predictiveConnectionKey:'9007199254740995',connectionId:1,valueA:0,valueB:0,flags:0,timingReliable:true,clockUncertaintySeconds:.001,networkEvidenceId:'Server:1:in:7',networkConfidence:.94,networkMatchBasis:'packet-content+net-object+time'}]

test.beforeEach(async({page})=>{await page.route('http://127.0.0.1:4174/api/**',async route=>{const path=new URL(route.request().url()).pathname;const body=path==='/api/workspace'?workspace:path==='/api/events'?{offset:0,limit:2000,total:1,items:events}:path==='/api/network'?{offset:0,limit:2000,total:1,items:[{id:'Server:1:in:7',endpoint:'Server',connectionId:1,direction:'in',packetIndex:7,sequence:99,time:1,bytes:64,content:['ServerTryActivateAbility']}]}:path==='/api/chains'?{offset:0,limit:500,total:1,items:[{id:'chain-1',key:'k',stages:[{eventId:events[0].id,endpoint:'Server',type:'AbilityActivated',time:1}],edges:[],complete:false}]}:path==='/api/diagnostics'?[{id:'D009',severity:'info',summary:'Evidence limited',evidenceId:events[0].id,confidence:.55,definitive:false}]:{};await route.fulfill({json:body})})})

test('loads real API contract, deep link and packet evidence',async({page})=>{await page.goto(`/?token=test&event=${encodeURIComponent(events[0].id)}`);await expect(page.getByText('capture-e2e')).toBeVisible();await expect(page.getByText('GA_Fire_C').first()).toBeVisible();await expect(page.getByText(/packet 99/)).toBeVisible();await page.getByRole('button',{name:'BOOKMARK'}).click();await expect(page.getByText('BOOKMARKS 1')).toBeVisible();expect(page.url()).toContain('event=Server%3A9007199254740993')})

test('shows token rejection state and reconnect action',async({page})=>{await page.unroute('http://127.0.0.1:4174/api/**');await page.route('http://127.0.0.1:4174/api/**',route=>route.fulfill({status:401,json:{error:'unauthorized'}}));await page.goto('/?token=bad');await expect(page.getByText('WORKSPACE UNAVAILABLE')).toBeVisible();await expect(page.getByRole('button',{name:'RECONNECT'})).toBeVisible()})
